local pages = {
  {
    title = "Navigation [1/5]",
    lines = {
      "  n/e/i/o        ←↓↑→ cursor              [N] B",
      "  w/b            next/prev word start     [N] B",
      "  f/p            next/prev word end       [N] B",
      "  0/$            start/end of line        [N] B",
      "  gg/G           first/last line          [N] B",
      "  {n}G           go to line               [N] B",
      "  %              matching bracket         [N] B",
      "  Ctrl+d/u       half page ↓/↑            [N] B",
      "  Ctrl+f/b       full page ↓/↑            [N] B",
      "  Ctrl+e/i       scroll line ↓/↑          [N] I",
      "  H/M/L          top/mid/bot screen       [N] I",
      "  zz/zt/zb       center/top/bot view      [N] I",
      "  {/}            paragraph prev/next      [N] I",
      "  (/)            sentence prev/next       [N] I",
    },
  },
  {
    title = "Insert Mode [2/5]",
    lines = {
      "  Entering Insert Mode",
      "  s/S            insert at cursor / bol   [N] B",
      "  a/A            append after cursor/eol  [N] B",
      "  r/R            new line below / above   [N] B",
      "  ga             append at end of word    [N] I",
      "  gi             insert at last position  [N] I",
      "",
      "  While Inserting",
      "  Ctrl+h         delete char before       [I] B",
      "  Ctrl+w         delete word before       [I] B",
      "  Ctrl+u         delete line before       [I] B",
      "  Ctrl+t/d       indent / un-indent       [I] I",
      "  Ctrl+r {reg}   insert from register     [I] I",
    },
  },
  {
    title = "Editing [3/5]",
    lines = {
      "  Replace & Join",
      "  r          replace char            [N] B",
      "  R          replace mode            [N] B",
      "  J          join line below         [N] B",
      "  gJ         join without space      [N] I",
      "",
      "  Change",
      "  cc/C       change line/to eol      [N] B",
      "  cw/ciw     change word/inner       [N] B",
      "  caw        change word+space       [N] I",
      "  ci\"/ci'    change inside quotes    [N] I",
      "  ci(/ci{/ci[  change inside brackets  [N] I",
      "  cit        change inside HTML tag       [N] A",
      "",
      "  Delete",
      "  dd/D       delete line/to eol      [N] B",
      "  dw/diw     delete word/inner       [N] B",
      "  daw        delete word+space       [N] I",
      "  di\"/da\"    inside/around quotes    [N] I",
      "  di(/da(    inside/around parens    [N] I",
      "  dit/dat    inside/around tag       [N] A",
      "",
      "  Misc",
      "  x/X        del char fwd/bwd        [N] B",
      "  s/S        del char/line+insert    [N] B",
      "  u/U        undo/undo line          [N] B",
      "  Ctrl+r     redo                    [N] B",
      "  .          repeat last command     [N] B",
      "  ~/g~       toggle case char/motion [N] I",
      "  gu/gU      lower/upper motion      [N] I",
      "  >>/<<      indent/dedent           [N] B",
      "  ==/gg=G    auto-indent line/file   [N] I",
    },
  },
  {
    title = "Visual Mode [4/5]",
    lines = {
      "  Entering Visual Mode",
      "  v              visual char mode         [N] B",
      "  V              visual line mode         [N] B",
      "  Ctrl+v         visual block mode        [N] I",
      "  gv             re-select last visual    [N] I",
      "",
      "  In Visual Mode",
      "  o/O            other end/corner         [V] I",
      "",
      "  Text Objects",
      "  aw             select a word            [V] B",
      "  ab/ib          block with/inner ()      [V] I",
      "  aB/iB          block with/inner {}      [V] I",
      "  at/it          block with/inner tags    [V] I",
      "",
      "  Actions",
      "  y/d/c          yank/delete/change       [V] B",
      "  >/<            indent/un-indent         [V] B",
      "  ~/u/U          toggle/lower/upper case  [V] I",
      "  I              block insert each line   [V] A",
      "  A              block append each line   [V] A",
      "  :              command mode for sel     [V] I",
    },
  },
{
  title = "Yank & Paste [4/6]",
  lines = {
    "  Yank",
    "  yy/Y           yank entire line         [N] B",
    "  yw/yiw         yank word/inner          [N] B",
    "  yaw            yank word with space      [N] I",
    "  y$/y^          yank to eol/bol          [N] B",
    "  yi\"/yi(        yank inside quotes/parens [N] I",
    "  yi{            yank inside braces       [N] I",
    "  yit            yank inside tag          [N] A",
    "",
    "  Paste",
    "  p/P            paste after/before       [N] B",
    "  gp/gP          paste and move cursor    [N] I",
    "  ]p/[p          paste with auto-indent   [N] I",
    "",
    "  Registers",
    "  \"_d{motion}    delete to black hole      [N] A",
    "  \"0p            paste from yank register  [N] A",
    "  \"+y/\"+p        yank/paste system clip    [N] I",
    "  \"*y/\"*p        yank/paste primary sel    [N] A",
  },
},
{
  title = "Search & Replace [5/6]",
  lines = {
    "  Search",
    "  /pattern       search forward            [N] B",
    "  ?pattern       search backward           [N] B",
    "  n/N            next/prev match           [N] B",
    "  */#            word under cursor fwd/bwd [N] B",
    "  g*/g#          partial word fwd/bwd      [N] I",
    "  gn             select next match         [N] I",
    "  cgn            change next match         [N] I",
    "  :noh           clear search              [C] B",
    "",
    "  Replace  (:%s/old/new/[flags])",
    "  :%s/old/new/g  replace all in file       [C] B",
    "  :%s/old/new/gc replace all+confirm       [C] B",
    "  :s/old/new/g   replace on current line   [C] B",
    "  :%s/old/new/gi replace case-insensitive  [C] I",
    "  :'<,'>s//new/g replace in selection      [C] I",
    "  :5,12s//new/g  replace in range          [C] I",
    "  :%s/\\<old\\>/g  whole word only           [C] A",
    "  :%s//new/g     reuse last pattern        [C] A",
    "  :g/pat/d       delete matching lines     [C] A",
    "  :v/pat/d       delete non-matching lines [C] A",
  },
},
{
  title = "File Operations [6/6]",
  lines = {
    "  Open & Reload",
    "  :e filename    open a file              [C] B",
    "  :e!            reload/discard changes   [C] B",
    "  :r filename    read file into buffer    [C] I",
    "  :r !command    read cmd output          [C] A",
    "",
    "  Save",
    "  :w             save file                [C] B",
    "  :w filename    save as filename         [C] B",
    "  :wa            save all files           [C] B",
    "  :saveas file   save as new filename     [C] I",
    "",
    "  Quit",
    "  :q/:q!         quit/without saving      [C] B",
    "  :wq/:x         save and quit            [C] B",
    "  ZZ/ZQ          save+quit/quit shortcut  [N] B",
    "  :qa/:qa!       quit all/without saving  [C] B",
    "  :wqa           save all and quit        [C] B",
    "",
    "  Directory & Time",
    "  :pwd           show current directory   [C] B",
    "  :cd path       change directory         [C] I",
    "  :lcd path      change dir for window    [C] A",
    "  :earlier 2m    file state 2min ago      [C] A",
    "  :later 2m      file state 2min later    [C] A",
  },
},
{
  title = "Buffers [7/7]",
  lines = {
    "  List",
    "  :ls/:buffers   list all buffers         [C] B",
    "",
    "  Switch",
    "  :b {n}         switch by number         [C] B",
    "  :b {name}      switch by name           [C] B",
    "  :bn/:bp        next/prev buffer         [C] B",
    "  :bf/:bl        first/last buffer        [C] I",
    "  Ctrl+^         switch to alternate      [N] I",
    "  :e #           edit alternate buffer    [C] I",
    "",
    "  Manage",
    "  :bd/:bd!       delete/force delete      [C] B",
    "  :%bd           delete all buffers       [C] I",
    "  :badd file     add file to list         [C] I",
    "  :ball          open all in windows      [C] A",
    "  :unhide        open all loaded          [C] A",
    "  :bufdo cmd     run cmd in all buffers   [C] A",
  },
},
{
  title = "Windows [8/8]",
  lines = {
    "  Split",
    "  :sp/:sp file   horiz split/with file    [C] B",
    "  :vs/:vs file   vert split/with file     [C] B",
    "  Ctrl+w s/v     horiz/vert split         [N] B",
    "",
    "  Navigate",
    "  Ctrl+w w       cycle windows            [N] B",
    "  Ctrl+w n/e/i/o move ←↓↑→               [N] B",
    "",
    "  Close",
    "  Ctrl+w q/c     close current window     [N] B",
    "  Ctrl+w o       close all others         [N] I",
    "",
    "  Resize",
    "  Ctrl+w =       equalize all windows     [N] I",
    "  Ctrl+w _/|     maximize height/width    [N] I",
    "  Ctrl+w +/-     increase/decrease height [N] I",
    "  Ctrl+w >/<     increase/decrease width  [N] I",
    "",
    "  Move",
    "  Ctrl+w H/L     move window far left/right[N] A",
    "  Ctrl+w K/J     move window top/bottom   [N] A",
    "  Ctrl+w r/R     rotate down/up           [N] A",
    "  Ctrl+w x       exchange windows         [N] A",
  },
},
{
  title = "Tabs [9/9]",
  lines = {
    "  Open & Close",
    "  :tabnew        open new tab             [C] B",
    "  :tabnew file   open file in new tab     [C] B",
    "  :tabc          close current tab        [C] B",
    "  :tabo          close all other tabs     [C] I",
    "",
    "  Navigate",
    "  gt/gT          next/prev tab            [N] B",
    "  {n}gt          go to tab {n}            [N] I",
    "  :tabs          list all tabs            [C] I",
    "",
    "  Move",
    "  :tabm {n}      move tab to position     [C] I",
    "  :tabm +1/-1    move tab right/left      [C] I",
    "  :tabdo cmd     run cmd in all tabs      [C] A",
  },
},
{
  title = "Marks & Jumps [10/10]",
  lines = {
    "  Set Marks",
    "  m{a-z}         set local mark           [N] I",
    "  m{A-Z}         set global mark          [N] I",
    "",
    "  Jump to Mark",
    "  `{mark}        exact position           [N] I",
    "  '{mark}        line of mark             [N] I",
    "  ``             last position before jump[N] I",
    "  `.             last change              [N] I",
    "  `^             last insert              [N] I",
    "  `[/`]          start/end last yank      [N] A",
    "  `</`>          start/end last visual    [N] A",
    "",
    "  Manage",
    "  :marks         list all marks           [C] I",
    "  :delmarks {m}  delete specified marks   [C] I",
    "  :delmarks!     delete all lower marks   [C] I",
    "",
    "  Jump List",
    "  Ctrl+o/i       older/newer position     [N] B",
    "  :jumps         show jump list           [C] I",
    "  :changes       show change list         [C] I",
    "  g;/g,          older/newer change pos   [N] I",
  },
},
{
  title = "Macros [11/11]",
  lines = {
    "  Record",
    "  q{a-z}         start recording to reg   [N] I",
    "  q              stop recording           [N] I",
    "  qA             append to register a     [N] A",
    "",
    "  Play",
    "  @{a-z}         play macro from reg      [N] I",
    "  @@             repeat last macro        [N] I",
    "  {n}@{a-z}      play macro {n} times     [N] I",
    "",
    "  Advanced",
    "  :reg {reg}          show register content     [C] I",
    "  :let @a='...'       set macro manually        [C] A",
    "  :'<,'>normal @a     run on visual selection   [C] A",
    "  :g/pattern/normal @a run on matching lines    [C] A",
  },
},
}

function open_cheatsheet(start_page)
  local current = start_page or 1
  local buf = vim.api.nvim_create_buf(false, true)

  local width = math.min(50, vim.o.columns - 4)
  local height = math.min(22, vim.o.lines - 4)
  local row = math.floor((vim.o.lines - height) / 2)
  local col = math.floor((vim.o.columns - width) / 2)

  local win = vim.api.nvim_open_win(buf, true, {
    relative = "editor",
    width = width, height = height,
    row = row, col = col,
    style = "minimal", border = "rounded",
    title = " Cheatsheet ", title_pos = "center",
    footer = " Tab/S-Tab · q to close ", footer_pos = "center",
  })

  local function render()
    local page = pages[current]
    local content = { "", "  " .. page.title, "  " .. string.rep("─", width - 4), "" }
    for _, line in ipairs(page.lines) do
      table.insert(content, line)
    end
    vim.bo[buf].modifiable = true
    vim.api.nvim_buf_set_lines(buf, 0, -1, false, content)
    vim.bo[buf].modifiable = false
  end

  render()

  local opts = { buffer = buf, silent = true, nowait = true }
  vim.keymap.set("n", "q", function() vim.api.nvim_win_close(win, true) end, opts)
  vim.keymap.set("n", "<Esc>", function() vim.api.nvim_win_close(win, true) end, opts)
  vim.keymap.set("n", "<Tab>", function()
    current = current % #pages + 1
    render()
  end, opts)
  vim.keymap.set("n", "<S-Tab>", function()
    current = (current - 2) % #pages + 1
    render()
  end, opts)
end
