local pages = {
  {
    title = "Navigation [1/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │      Basic Motion        │",
      "  ╰──────────────────────────╯",
      "  n/e/i/o        ←↓↑→ cursor              [N] B",
      "  w/b            next/prev word start     [N] B",
      "  f/p            next/prev word end       [N] B",
      "  0/$            start/end of line        [N] B",
      "  ^/g_           first/last non-blank     [N] B",
      "",
      "  ╭──────────────────────────╮",
      "  │          Jump            │",
      "  ╰──────────────────────────╯",
      "  gg/G           first/last line          [N] B",
      "  {n}G           go to line               [N] B",
      "  %              matching bracket         [N] B",
      "  {/}            paragraph prev/next      [N] I",
      "  (/)            sentence prev/next       [N] I",
      "  gf             go to file under cursor  [N] I",
      "  gx             open URL under cursor    [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │         Scroll           │",
      "  ╰──────────────────────────╯",
      "  Ctrl+d/u       half page ↓/↑            [N] B",
      "  Ctrl+f/b       full page ↓/↑            [N] B",
      "  Ctrl+e/i       scroll line ↓/↑          [N] I",
      "  H/M/L          top/mid/bot screen       [N] I",
      "  zz/zt/zb       center/top/bot view      [N] I",
    },
  },
  {
    title = "Insert Mode [2/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │   Entering Insert Mode   │",
      "  ╰──────────────────────────╯",
      "  s/S            insert at cursor/bol     [N] B",
      "  a/A            append after cursor/eol  [N] B",
      "  r/R            new line below/above     [N] B",
      "  ga             append at end of word    [N] I",
      "  gi             insert at last position  [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │     While Inserting      │",
      "  ╰──────────────────────────╯",
      "  Ctrl+h         delete char before       [I] B",
      "  Ctrl+w         delete word before       [I] B",
      "  Ctrl+u         delete to line start     [I] B",
      "  Ctrl+t/d       indent/un-indent         [I] I",
      "  Ctrl+r {reg}   insert from register     [I] I",
      "  Ctrl+a         re-insert last insert    [I] I",
      "  Ctrl+o         one normal cmd → insert  [I] I",
    },
  },
  {
    title = "Editing [3/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │     Replace & Join       │",
      "  ╰──────────────────────────╯",
      "  r              replace char             [N] B",
      "  R              replace mode             [N] B",
      "  J              join line below          [N] B",
      "  gJ             join without space       [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │         Change           │",
      "  ╰──────────────────────────╯",
      "  cc/C           change line/to eol       [N] B",
      "  cw             change word              [N] B",
      "",
      "  ╭──────────────────────────╮",
      "  │         Delete           │",
      "  ╰──────────────────────────╯",
      "  dd/D           delete line/to eol       [N] B",
      "  dw             delete word              [N] B",
      "  x/X            del char fwd/bwd         [N] B",
      "",
      "  ╭──────────────────────────╮",
      "  │   Undo, Repeat & Misc    │",
      "  ╰──────────────────────────╯",
      "  u/Ctrl+r       undo/redo                [N] B",
      "  U              undo all on line         [N] I",
      "  .              repeat last command      [N] B",
      "  Ctrl+a/Ctrl+x  increment/decrement num  [N] B",
      "  ~/g~{motion}   toggle case char/motion  [N] I",
      "  gu/gU          lower/upper motion       [N] I",
      "  >>/<<          indent/dedent            [N] B",
      "  ==/gg=G        auto-indent line/file    [N] I",
      "  gq{motion}     format/wrap text         [N] I",
    },
  },
  {
    title = "Visual Mode [4/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │   Entering Visual Mode   │",
      "  ╰──────────────────────────╯",
      "  v              visual char mode         [N] B",
      "  V              visual line mode         [N] B",
      "  Ctrl+v         visual block mode        [N] I",
      "  gv             re-select last visual    [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │      In Visual Mode      │",
      "  ╰──────────────────────────╯",
      "  o/O            other end/corner         [V] I",
      "",
      "  ╭──────────────────────────╮",
      "  │       Text Objects       │",
      "  ╰──────────────────────────╯",
      "  aw             select a word            [V] B",
      "  ab/ib          block with/inner ()      [V] I",
      "  aB/iB          block with/inner {}      [V] I",
      "  at/it          block with/inner tags    [V] I",
      "",
      "  ╭──────────────────────────╮",
      "  │         Actions          │",
      "  ╰──────────────────────────╯",
      "  y/d/c          yank/delete/change       [V] B",
      "  >/<            indent/un-indent         [V] B",
      "  ~/u/U          toggle/lower/upper case  [V] I",
      "  r{char}        replace all selected     [V] I",
      "  I              block insert each line   [V] A",
      "  A              block append each line   [V] A",
      "  :              command mode for sel     [V] I",
    },
  },
  {
    title = "Text Objects [5/21]",
    lines = {
      "  Use with operators: d/c/y/v + i(nner)/a(round)",
      "",
      "  ╭──────────────────────────╮",
      "  │          Words           │",
      "  ╰──────────────────────────╯",
      "  iw/aw          inner/around word        [N] B",
      "  iW/aW          inner/around WORD        [N] I",
      "  is/as          inner/around sentence    [N] I",
      "  ip/ap          inner/around paragraph   [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │        Brackets          │",
      "  ╰──────────────────────────╯",
      "  i(/a(          inner/around ()          [N] B",
      "  i[/a[          inner/around []          [N] B",
      "  i{/a{          inner/around {}          [N] B",
      "  i</a<          inner/around <>          [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │         Quotes           │",
      "  ╰──────────────────────────╯",
      "  i\"/a\"          inner/around \"\"          [N] B",
      "  i'/a'          inner/around ''          [N] B",
      "  i`/a`          inner/around ``          [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │          Tags            │",
      "  ╰──────────────────────────╯",
      "  it/at          inner/around tag         [N] I",
    },
  },
  {
    title = "Yank & Paste [6/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │          Yank            │",
      "  ╰──────────────────────────╯",
      "  yy/Y           yank entire line         [N] B",
      "  yw             yank word                [N] B",
      "  y$/y^          yank to eol/bol          [N] B",
      "",
      "  ╭──────────────────────────╮",
      "  │          Paste           │",
      "  ╰──────────────────────────╯",
      "  p/P            paste after/before       [N] B",
      "  gp/gP          paste and move cursor    [N] I",
      "  ]p/[p          paste with auto-indent   [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │        Registers         │",
      "  ╰──────────────────────────╯",
      "  \"_d{motion}    delete to black hole     [N] A",
      "  \"0p            paste from yank register [N] A",
      "  \"+y/\"+p        yank/paste system clip   [N] I",
      "  \"*y/\"*p        yank/paste primary sel   [N] A",
    },
  },
  {
    title = "Search & Replace [7/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │         Search           │",
      "  ╰──────────────────────────╯",
      "  /pattern       search forward           [N] B",
      "  ?pattern       search backward          [N] B",
      "  n/N            next/prev match          [N] B",
      "  */#            word under cursor fwd/bwd[N] B",
      "  g*/g#          partial word fwd/bwd     [N] I",
      "  gn             select next match        [N] I",
      "  cgn            change next match        [N] I",
      "  :noh           clear search highlight   [C] B",
      "",
      "  ╭──────────────────────────╮",
      "  │  Replace :%s/old/new/[]  │",
      "  ╰──────────────────────────╯",
      "  :%s/old/new/g  replace all in file      [C] B",
      "  :%s/old/new/gc replace all+confirm      [C] B",
      "  :s/old/new/g   replace on current line  [C] B",
      "  :%s/old/new/gi replace case-insensitive [C] I",
      "  :'<,'>s//new/g replace in selection     [C] I",
      "  :5,12s//new/g  replace in range         [C] I",
      "  :%s/\\<old\\>/g  whole word only          [C] A",
      "  :%s//new/g     reuse last pattern       [C] A",
      "  :g/pat/d       delete matching lines    [C] A",
      "  :v/pat/d       delete non-matching      [C] A",
    },
  },
  {
    title = "File Operations [8/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │      Open & Reload       │",
      "  ╰──────────────────────────╯",
      "  :e filename    open a file              [C] B",
      "  :e!            reload/discard changes   [C] B",
      "  :r filename    read file into buffer    [C] I",
      "  :r !command    read cmd output          [C] A",
      "",
      "  ╭──────────────────────────╮",
      "  │          Save            │",
      "  ╰──────────────────────────╯",
      "  :w             save file                [C] B",
      "  :w filename    save as filename         [C] B",
      "  :wa            save all files           [C] B",
      "  :saveas file   save as new filename     [C] I",
      "",
      "  ╭──────────────────────────╮",
      "  │          Quit            │",
      "  ╰──────────────────────────╯",
      "  :q/:q!         quit/without saving      [C] B",
      "  :wq/:x         save and quit            [C] B",
      "  ZZ/ZQ          save+quit/quit shortcut  [N] B",
      "  :qa/:qa!       quit all/without saving  [C] B",
      "  :wqa           save all and quit        [C] B",
      "",
      "  ╭──────────────────────────╮",
      "  │    Directory & Time      │",
      "  ╰──────────────────────────╯",
      "  :pwd           show current directory   [C] B",
      "  :cd path       change directory         [C] I",
      "  :lcd path      change dir for window    [C] A",
      "  :earlier 2m    file state 2min ago      [C] A",
      "  :later 2m      file state 2min later    [C] A",
    },
  },
  {
    title = "Buffers [9/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │          List            │",
      "  ╰──────────────────────────╯",
      "  :ls/:buffers   list all buffers         [C] B",
      "",
      "  ╭──────────────────────────╮",
      "  │         Switch           │",
      "  ╰──────────────────────────╯",
      "  :b {n}         switch by number         [C] B",
      "  :b {name}      switch by name           [C] B",
      "  :bn/:bp        next/prev buffer         [C] B",
      "  :bf/:bl        first/last buffer        [C] I",
      "  Ctrl+^         switch to alternate      [N] I",
      "  :e #           edit alternate buffer    [C] I",
      "",
      "  ╭──────────────────────────╮",
      "  │         Manage           │",
      "  ╰──────────────────────────╯",
      "  :bd/:bd!       delete/force delete      [C] B",
      "  :%bd           delete all buffers       [C] I",
      "  :badd file     add file to list         [C] I",
      "  :ball          open all in windows      [C] A",
      "  :unhide        open all loaded          [C] A",
      "  :bufdo cmd     run cmd in all buffers   [C] A",
    },
  },
  {
    title = "Windows [10/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │          Split           │",
      "  ╰──────────────────────────╯",
      "  :sp/:sp file   horiz split/with file    [C] B",
      "  :vs/:vs file   vert split/with file     [C] B",
      "  Ctrl+w s/v     horiz/vert split         [N] B",
      "",
      "  ╭──────────────────────────╮",
      "  │        Navigate          │",
      "  ╰──────────────────────────╯",
      "  Ctrl+w w       cycle windows            [N] B",
      "  Ctrl+w n/e/i/o move ←↓↑→               [N] B",
      "",
      "  ╭──────────────────────────╮",
      "  │          Close           │",
      "  ╰──────────────────────────╯",
      "  Ctrl+w q/c     close current window     [N] B",
      "  Ctrl+w o       close all others         [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │         Resize           │",
      "  ╰──────────────────────────╯",
      "  Ctrl+w =       equalize all windows     [N] I",
      "  Ctrl+w _/|     maximize height/width    [N] I",
      "  Ctrl+w +/-     increase/decrease height [N] I",
      "  Ctrl+w >/<     increase/decrease width  [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │          Move            │",
      "  ╰──────────────────────────╯",
      "  Ctrl+w H/L     move window far left/right[N] A",
      "  Ctrl+w K/J     move window top/bottom   [N] A",
      "  Ctrl+w r/R     rotate down/up           [N] A",
      "  Ctrl+w x       exchange windows         [N] A",
    },
  },
  {
    title = "Tabs [11/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │      Open & Close        │",
      "  ╰──────────────────────────╯",
      "  :tabnew        open new tab             [C] B",
      "  :tabnew file   open file in new tab     [C] B",
      "  :tabc          close current tab        [C] B",
      "  :tabo          close all other tabs     [C] I",
      "",
      "  ╭──────────────────────────╮",
      "  │        Navigate          │",
      "  ╰──────────────────────────╯",
      "  gt/gT          next/prev tab            [N] B",
      "  {n}gt          go to tab {n}            [N] I",
      "  :tabs          list all tabs            [C] I",
      "",
      "  ╭──────────────────────────╮",
      "  │          Move            │",
      "  ╰──────────────────────────╯",
      "  :tabm {n}      move tab to position     [C] I",
      "  :tabm +1/-1    move tab right/left      [C] I",
      "  :tabdo cmd     run cmd in all tabs      [C] A",
    },
  },
  {
    title = "Marks & Jumps [12/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │        Set Marks         │",
      "  ╰──────────────────────────╯",
      "  m{a-z}         set local mark           [N] I",
      "  m{A-Z}         set global mark          [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │      Jump to Mark        │",
      "  ╰──────────────────────────╯",
      "  `{mark}        exact position           [N] I",
      "  '{mark}        line of mark             [N] I",
      "  ``             last position before jump[N] I",
      "  `.             last change              [N] I",
      "  `^             last insert              [N] I",
      "  `[/`]          start/end last yank      [N] A",
      "  `</`>          start/end last visual    [N] A",
      "",
      "  ╭──────────────────────────╮",
      "  │         Manage           │",
      "  ╰──────────────────────────╯",
      "  :marks         list all marks           [C] I",
      "  :delmarks {m}  delete specified marks   [C] I",
      "  :delmarks!     delete all lower marks   [C] I",
      "",
      "  ╭──────────────────────────╮",
      "  │        Jump List         │",
      "  ╰──────────────────────────╯",
      "  Ctrl+o/i       older/newer position     [N] B",
      "  :jumps         show jump list           [C] I",
      "  :changes       show change list         [C] I",
      "  g;/g,          older/newer change pos   [N] I",
    },
  },
  {
    title = "Macros [13/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │         Record           │",
      "  ╰──────────────────────────╯",
      "  q{a-z}         start recording to reg   [N] I",
      "  q              stop recording           [N] I",
      "  qA             append to register a     [N] A",
      "",
      "  ╭──────────────────────────╮",
      "  │          Play            │",
      "  ╰──────────────────────────╯",
      "  @{a-z}         play macro from reg      [N] I",
      "  @@             repeat last macro        [N] I",
      "  {n}@{a-z}      play macro {n} times     [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │        Advanced          │",
      "  ╰──────────────────────────╯",
      "  :reg {reg}          show register content    [C] I",
      "  :let @a='...'       set macro manually       [C] A",
      "  :'<,'>normal @a     run on visual selection  [C] A",
      "  :g/pattern/normal @a run on matching lines   [C] A",
    },
  },
  {
    title = "Registers [14/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │          Usage           │",
      "  ╰──────────────────────────╯",
      "  \"{reg}y{motion} yank to register        [N] I",
      "  \"{reg}p         paste from register     [N] I",
      "  :reg            show all registers      [C] I",
      "  Ctrl+r {reg}    insert register         [I] I",
      "",
      "  ╭──────────────────────────╮",
      "  │    Named Registers       │",
      "  ╰──────────────────────────╯",
      "  \"0             last yank               [N] I",
      "  \"1-9           last deletes            [N] A",
      "  \"-             small delete            [N] A",
      "",
      "  ╭──────────────────────────╮",
      "  │   Special Registers      │",
      "  ╰──────────────────────────╯",
      "  \"+             system clipboard        [N] B",
      "  \"*             primary selection       [N] I",
      "  \"_             black hole              [N] I",
      "  \"=             expression register     [N] A",
      "",
      "  ╭──────────────────────────╮",
      "  │   Read-only Registers    │",
      "  ╰──────────────────────────╯",
      "  \"/             last search pattern     [N] A",
      "  \":             last command            [N] A",
      "  \".             last inserted text      [N] A",
      "  \"%             current filename        [N] A",
      "  \"#             alternate filename      [N] A",
    },
  },
  {
    title = "Folding [15/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │     Create & Delete      │",
      "  ╰──────────────────────────╯",
      "  zf{motion}     create fold with motion  [N] I",
      "  zf             create fold from visual  [V] I",
      "  zd/zD          delete fold/all under    [N] I",
      "  zE             delete all folds in file [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │      Open & Close        │",
      "  ╰──────────────────────────╯",
      "  zo/zO          open fold/all under      [N] B",
      "  zc/zC          close fold/all under     [N] B",
      "  za/zA          toggle fold/all under    [N] B",
      "  zR             open all folds           [N] I",
      "  zM             close all folds          [N] I",
      "  zr/zm          reduce/increase level    [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │    Enable & Navigate     │",
      "  ╰──────────────────────────╯",
      "  zn/zN          disable/enable folding   [N] I",
      "  [z/]z          start/end of fold        [N] I",
      "  zj/zk          next/prev fold           [N] I",
    },
  },
  {
    title = "Command Line [16/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │       Help & Info        │",
      "  ╰──────────────────────────╯",
      "  :h topic       open help for topic      [C] B",
      "  :version       show neovim version      [C] B",
      "  :checkhealth   run health check         [C] B",
      "  Ctrl+g         show file info/position  [N] B",
      "",
      "  ╭──────────────────────────╮",
      "  │         Options          │",
      "  ╰──────────────────────────╯",
      "  :set option    set an option            [C] B",
      "  :set option?   show option value        [C] B",
      "  :set option!   toggle boolean option    [C] I",
      "  :set nooption  disable option           [C] I",
      "  :set all       show all options         [C] I",
      "",
      "  ╭──────────────────────────╮",
      "  │    Shell & History       │",
      "  ╰──────────────────────────╯",
      "  :!cmd          execute shell command    [C] I",
      "  :r !cmd        insert command output    [C] I",
      "  :terminal      open terminal            [C] B",
      "  :%!cmd         filter buffer through cmd[C] A",
      "  :'<,'>!cmd     filter selection         [C] A",
      "  q:             command-line history     [N] I",
      "  q/             search history           [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │          Misc            │",
      "  ╰──────────────────────────╯",
      "  :sort/:sort!   sort/reverse sort        [C] I",
      "  :sort u        sort remove duplicates   [C] I",
      "  :norm cmd      normal cmd on line       [C] A",
      "  :%norm cmd     normal cmd all lines     [C] A",
      "  :source file   execute from file        [C] I",
    },
  },
  {
    title = "LSP [17/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │       Navigation         │",
      "  ╰──────────────────────────╯",
      "  gd/gD          go to definition/decl    [N] B",
      "  gr             go to references         [N] B",
      "  gi             go to implementation     [N] B",
      "",
      "  ╭──────────────────────────╮",
      "  │      Information         │",
      "  ╰──────────────────────────╯",
      "  K              show hover info          [N] B",
      "  Ctrl+k         show signature help      [N] I",
      "  ga             show char ASCII info     [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │         Actions          │",
      "  ╰──────────────────────────╯",
      "  <leader>rn     rename symbol            [N] B",
      "  <leader>ca     code action              [N] B",
      "  <leader>f      format document          [N] B",
      "",
      "  ╭──────────────────────────╮",
      "  │      Diagnostics         │",
      "  ╰──────────────────────────╯",
      "  [d/]d          prev/next diagnostic     [N] B",
      "  <leader>e      show diagnostic float    [N] I",
      "  <leader>q      diagnostics to quickfix  [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │         Server           │",
      "  ╰──────────────────────────╯",
      "  :LspInfo       show LSP information     [C] I",
      "  :LspRestart    restart LSP client       [C] I",
      "  :LspStart/Stop start/stop LSP client    [C] I",
    },
  },
  {
    title = "Completion [18/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │          Basic           │",
      "  ╰──────────────────────────╯",
      "  Ctrl+n/p       next/prev item           [I] B",
      "  Ctrl+y         confirm completion       [I] B",
      "  Ctrl+e         cancel completion        [I] B",
      "",
      "  ╭──────────────────────────╮",
      "  │       Ctrl+x Mode        │",
      "  ╰──────────────────────────╯",
      "  Ctrl+x Ctrl+o  omni completion          [I] I",
      "  Ctrl+x Ctrl+f  filename completion      [I] I",
      "  Ctrl+x Ctrl+l  line completion          [I] I",
      "  Ctrl+x Ctrl+n  keyword (current file)   [I] I",
      "  Ctrl+x Ctrl+k  dictionary completion    [I] A",
      "  Ctrl+x Ctrl+]  tag completion           [I] A",
      "  Ctrl+x Ctrl+i  keyword (includes)       [I] A",
    },
  },
  {
    title = "Spell & Quickfix [19/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │       Spell Check        │",
      "  ╰──────────────────────────╯",
      "  :set spell     enable spell checking    [C] B",
      "  :set nospell   disable spell checking   [C] B",
      "  ]s/[s          next/prev misspelled     [N] B",
      "  z=             suggest corrections      [N] B",
      "  1z=            use first suggestion     [N] I",
      "  :spellr        repeat replacement all   [C] I",
      "  zg             add word to dictionary   [N] B",
      "  zw             mark word as wrong       [N] I",
      "  zug            undo add to dictionary   [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │  Quickfix / Location     │",
      "  ╰──────────────────────────╯",
      "  :copen/:cclose open/close quickfix      [C] B",
      "  :cnext/:cprev  next/prev item           [C] B",
      "  :cfirst/:clast first/last item          [C] I",
      "  :colder/:cnewer older/newer list        [C] A",
      "  :lopen/:lclose open/close loc list      [C] I",
      "  :lnext/:lprev  next/prev loc item       [C] I",
      "  :make          run makeprg → quickfix   [C] I",
      "  :grep pattern  grep → quickfix          [C] I",
      "  :vimgrep pat % vimgrep current file     [C] I",
    },
  },
  {
    title = "Diff [20/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │          Setup           │",
      "  ╰──────────────────────────╯",
      "  nvim -d f1 f2  start in diff mode       [C] B",
      "  :diffthis      add window to diff       [C] I",
      "  :diffoff       remove window from diff  [C] I",
      "  :diffupdate    update highlighting      [C] I",
      "",
      "  ╭──────────────────────────╮",
      "  │        Navigate          │",
      "  ╰──────────────────────────╯",
      "  ]c/[c          next/prev change         [N] B",
      "",
      "  ╭──────────────────────────╮",
      "  │          Merge           │",
      "  ╰──────────────────────────╯",
      "  do             obtain change from other [N] I",
      "  dp             put change to other      [N] I",
      "  :diffget       get changes from buffer  [C] I",
      "  :diffput       put changes to buffer    [C] I",
    },
  },
  {
    title = "Neovim Specific [21/21]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │        Terminal          │",
      "  ╰──────────────────────────╯",
      "  :terminal      open embedded terminal   [C] B",
      "  i              enter terminal insert    [N] B",
      "  Ctrl+\\ Ctrl+n  exit terminal to normal  [*] B",
      "",
      "  ╭──────────────────────────╮",
      "  │        LSP Lua           │",
      "  ╰──────────────────────────╯",
      "  :lua vim.lsp.buf.format()      format   [C] I",
      "  :lua vim.diagnostic.open_float() diag   [C] I",
      "  :lua print(vim.inspect(...))   debug    [C] A",
      "  :lua =...      quick print expression   [C] I",
      "",
      "  ╭──────────────────────────╮",
      "  │        Telescope         │",
      "  ╰──────────────────────────╯",
      "  :Telescope find_files  fuzzy find files [C] B",
      "  :Telescope live_grep   live grep        [C] B",
      "  :Telescope buffers     list buffers     [C] B",
      "",
      "  ╭──────────────────────────╮",
      "  │    g Commands Grab Bag   │",
      "  ╰──────────────────────────╯",
      "  g&             repeat last :s globally  [N] A",
      "  gq{motion}     format/wrap text         [N] I",
      "  gf             go to file under cursor  [N] I",
      "  gx             open URL under cursor    [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │          Misc            │",
      "  ╰──────────────────────────╯",
      "  :Lazy          package manager          [C] I",
      "  :Mason         LSP installer            [C] I",
      "  :so %          source current file      [C] I",
      "  :messages      view message history     [C] B",
      "  :Notifications view notifications       [C] B",
    },
  },
  {
    title = "Plugins: JJ [28/28]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │       Log Buffer         │",
      "  ╰──────────────────────────╯",
      "  <CR>           checkout revision         [N] B",
      "  d              describe revision         [N] B",
      "  D              diff revision             [N] I",
      "  e              edit revision             [N] B",
      "  n              new change (branch off)   [N] B",
      "  a              abandon revision          [N] I",
      "  b              bookmark at revision      [N] I",
      "  r              enter rebase mode         [N] I",
      "  s              enter squash mode         [N] I",
      "  S              quick squash to parent    [N] I",
      "  <C-s>          split revision            [N] A",
      "  f / p          fetch / push              [N] B",
      "  P              push all                  [N] I",
      "  o / O          open PR / PR list         [N] I",
      "  K              summary tooltip           [N] I",
      "  U / R          undo / redo               [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │        Commands          │",
      "  ╰──────────────────────────╯",
      "  :J status      show status               [C] B",
      "  :J log         show log                  [C] B",
      "  :J new         new change                [C] B",
      "  :J commit      describe + new            [C] B",
      "  :J push / fetch  push / fetch            [C] B",
      "  :J split       split interactively       [C] I",
      "  :Jdiff @-      diff against parent       [C] I",
      "  :Jvdiff main   vertical diff vs main     [C] I",
      "  :Jbrowse       open file on remote       [C] I",
    },
  },
  {
    title = "Plugins: Hunk [27/28]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │         Global           │",
      "  ╰──────────────────────────╯",
      "  q              quit                      [N] B",
      "  <leader><CR>   accept changes            [N] B",
      "  <leader>e      focus tree                [N] B",
      "",
      "  ╭──────────────────────────╮",
      "  │          Tree            │",
      "  ╰──────────────────────────╯",
      "  l / <Right>    expand node               [N] B",
      "  h / <Left>     collapse node             [N] B",
      "  <CR>           open file                 [N] B",
      "  a              toggle file               [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │          Diff            │",
      "  ╰──────────────────────────╯",
      "  A              toggle hunk               [N] I",
      "  a              toggle line               [N] I",
      "  s              toggle line pair           [N] I",
      "  [h / ]h        prev/next hunk            [N] B",
      "  <Tab>          toggle focus L/R          [N] I",
    },
  },
  {
    title = "Plugins: Trouble [25/28]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │       Diagnostics        │",
      "  ╰──────────────────────────╯",
      "  <leader>xx     toggle diagnostics        [N] B",
      "  <leader>xX     buffer diagnostics        [N] B",
      "",
      "  ╭──────────────────────────╮",
      "  │        Symbols           │",
      "  ╰──────────────────────────╯",
      "  <leader>cs     toggle symbols            [N] I",
      "  <leader>cl     LSP def/refs/...          [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │         Lists            │",
      "  ╰──────────────────────────╯",
      "  <leader>xL     toggle location list      [N] I",
      "  <leader>xQ     toggle quickfix list      [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │    Advanced Commands      │",
      "  ╰──────────────────────────╯",
      "  :Trouble diagnostics filter.buf=0        [C] I",
      "  :Trouble symbols pinned=true             [C] A",
      "  :Trouble diagnostics filter.severity=ERR [C] A",
      "  :Trouble diagnostics win.type=split      [C] A",
    },
  },
  {
    title = "Plugins: Oil [23/28]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │          Open            │",
      "  ╰──────────────────────────╯",
      "  -              open parent directory     [N] B",
      "",
      "  ╭──────────────────────────╮",
      "  │       Navigation         │",
      "  ╰──────────────────────────╯",
      "  <CR>           select entry              [N] B",
      "  -              go to parent              [N] B",
      "  _              open cwd                  [N] I",
      "  `              cd to directory            [N] I",
      "  g~             cd (tab scope)            [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │         Actions          │",
      "  ╰──────────────────────────╯",
      "  <C-s>          open vertical split       [N] B",
      "  <C-h>          open horizontal split     [N] B",
      "  <C-t>          open in new tab           [N] I",
      "  <C-p>          preview file              [N] I",
      "  <C-c>          close oil                 [N] B",
      "  <C-l>          refresh                   [N] I",
      "",
      "  ╭──────────────────────────╮",
      "  │        Toggles           │",
      "  ╰──────────────────────────╯",
      "  g?             show help                 [N] B",
      "  gs             change sort               [N] I",
      "  gx             open external             [N] I",
      "  g.             toggle hidden files       [N] I",
      "  g\\             toggle trash              [N] I",
    },
  },
  {
    title = "Plugins: Spectre [24/28]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │          Open            │",
      "  ╰──────────────────────────╯",
      "  <leader>S      toggle Spectre            [N] B",
      "  :Spectre       toggle Spectre            [C] B",
      "",
      "  ╭──────────────────────────╮",
      "  │         Search           │",
      "  ╰──────────────────────────╯",
      "  <leader>sw     search current word       [N] B",
      "  <leader>sw     search current word       [V] B",
      "  <leader>sp     search in current file    [N] I",
    },
  },
  {
    title = "Plugins: MarkdownPreview [24/28]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │          Manage          │",
      "  ╰──────────────────────────╯",
      "  :MarkdownPreview       start preview     [C] B",
      "  :MarkdownPreviewStop   stop preview      [C] B",
      "  :MarkdownPreviewToggle toggle preview    [C] B",
    },
  },
  {
    title = "Plugins: Which Keys [22/23]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │          Open            │",
      "  ╰──────────────────────────╯",
      "  g?             toggle Spectre            [N] B",
    },
  },
  {
    title = "Plugins: Commentary [22/23]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │         Comment          │",
      "  ╰──────────────────────────╯",
      "  gcc            toggle comment line       [N] B",
      "  gc{motion}     toggle comment motion     [N] B",
      "  gc             toggle comment            [V] B",
    },
  },
  {
    title = "Plugins: Notify [22/23]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │        Telescope         │",
      "  ╰──────────────────────────╯",
      "  :Telescope notify  browse notifications  [C] I",
    },
  },
  {
    title = "Plugins: Inc Rename [22/23]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │          Rename          │",
      "  ╰──────────────────────────╯",
      "  <leader>rn     incremental rename        [N] B",
      "  :IncRename     rename via command         [C] B",
    },
  },
  {
    title = "Plugins: Cmp [22/23]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │          Manage          │",
      "  ╰──────────────────────────╯",
      "  Ctrl+b/f       scroll docs ↑/↓           [I] B",
      "  Ctrl+Space     trigger completion        [I] B",
      "  Ctrl+e         abort completion          [I] B",
      "  <CR>           confirm selected          [I] B",
    },
  },
  {
    title = "Plugins: Mermaid [22/23]",
    lines = {
      "  ╭──────────────────────────╮",
      "  │          Manage          │",
      "  ╰──────────────────────────╯",
      "  :MermaiderRender   render diagram        [C] I",
      "  :MermaiderPreview  preview diagram       [C] I",
      "  :MermaiderToggle   toggle code/diagram   [C] I",
      "  <leader>mt         toggle view            [N] I",
    },
  },

  -- {
  --   title = "Plugins: Action Preview [22/23]",
  --   lines = {
  --     "  ╭──────────────────────────╮",
  --     "  │          Open            │",
  --     "  ╰──────────────────────────╯",
  --     "  ga             code actions preview      [N/V] B",
  --   },
  -- },
  -- {
  --   title = "Which Keys [22/23]",
  --   lines = {
  --     "  ╭──────────────────────────╮",
  --     "  │        Actions Preview          │",
  --     "  ╰──────────────────────────╯",
  --   vim.keymap.set({ "v", "n" }, "ga", require("actions-preview").code_actions)


  --     "  ╭──────────────────────────╮",
  --     "  │        Inc Rename          │",
  --     "  ╰──────────────────────────╯",
-- vim.keymap.set("n", "<leader>rn", ":IncRename ")

  --     "  ╭──────────────────────────╮",
  --     "  │        Oil        │",
  --     "  ╰──────────────────────────╯",
-- vim.keymap.set("n", "-", "<CMD>Oil<CR>", { desc = "Open parent directory" })

  --     "  ╭──────────────────────────╮",
  --     "  │      Rustaceanvim        │",
  --     "  ╰──────────────────────────╯",
-- local bufnr = vim.api.nvim_get_current_buf()
-- vim.keymap.set(
  -- "n",
  -- "<leader>a",
  -- function()
  --   vim.cmd.RustLsp('codeAction') -- supports rust-analyzer's grouping
  --   -- or vim.lsp.buf.codeAction() if you don't want grouping.
  -- end,
  -- { silent = true, buffer = bufnr }
-- )
-- vim.keymap.set(
  -- "n",
  -- "K",  -- Override Neovim's built-in hover keymap with rustaceanvim's hover actions
  -- function()
  --   vim.cmd.RustLsp({'hover', 'actions'})
  -- end,
  -- { silent = true, buffer = bufnr }
-- )

-- Spectre 
-- vim.keymap.set('n', '<leader>S', '<cmd>lua require("spectre").toggle()<CR>', {
  --   desc = "Toggle Spectre"
-- })
-- vim.keymap.set('n', '<leader>sw', '<cmd>lua require("spectre").open_visual({select_word=true})<CR>', {
  --   desc = "Search current word"
-- })
-- vim.keymap.set('v', '<leader>sw', '<esc><cmd>lua require("spectre").open_visual()<CR>', {
  --   desc = "Search current word"
-- })
-- vim.keymap.set('n', '<leader>sp', '<cmd>lua require("spectre").open_file_search({select_word=true})<CR>', {
  --   desc = "Search on current file"
-- })
  --   },
  -- },

  -- Rest
-- User Command 	Behavior
-- :Rest open 	Open result pane
-- :Rest run 	Run request under the cursor
-- :Rest run {name} 	Run request with name {name}
-- :Rest last 	Run last request
-- :Rest logs 	Edit logs file
-- :Rest cookies 	Edit cookies file
-- :Rest env show 	Show dotenv file registered to current .http file
-- :Rest env select 	Select & register .env file with vim.ui.select()
-- :Rest env set {path} 	Register .env file to current .http file



  -- {
  --   title = "Git Plugins [22/25]",
  --   lines = {
  --     "  Neogit",
  --     "  :Neogit                open neogit       [C] B",
  --     "  :Neogit commit         commit popup      [C] B",
  --     "  :Neogit pull/push      pull/push popup   [C] I",
  --     "  :Neogit log            log popup         [C] I",
  --     "",
  --     "  Gitsigns (in-buffer signs)",
  --     "  ]c/[c          next/prev hunk           [N] B",
  --     "  :Gitsigns stage_hunk       stage hunk   [C] B",
  --     "  :Gitsigns reset_hunk       reset hunk   [C] B",
  --     "  :Gitsigns undo_stage_hunk  unstage      [C] I",
  --     "  :Gitsigns preview_hunk     preview      [C] B",
  --     "  :Gitsigns blame_line       inline blame [C] B",
  --     "  :Gitsigns toggle_current_line_blame     [C] I",
  --     "  :Gitsigns diffthis         diff vs index[C] I",
  --     "  :Gitsigns stage_buffer     stage all    [C] I",
  --     "  :Gitsigns reset_buffer     reset all    [C] I",
  --     "",
  --     "  Hunk (side-by-side diff)",
  --     "  :HunkDiff              open diff view    [C] I",
  --   },
  -- },
  -- {
  --   title = "File & Search Plugins [23/25]",
  --   lines = {
  --     "  Oil (file manager)",
  --     "  :Oil           open parent directory     [C] B",
  --     "  <CR>           open file/directory       [O] B",
  --     "  -              go to parent directory    [O] B",
  --     "  g.             toggle hidden files       [O] I",
  --     "  Ctrl+p         preview file              [O] I",
  --     "  Ctrl+c         close oil                 [O] B",
  --     "  Ctrl+l         refresh listing           [O] I",
  --     "  Ctrl+s         save changes (write)      [O] B",
  --     "",
  --     "  Spectre (project search & replace)",
  --     "  :Spectre                 toggle panel    [C] B",
  --     "  :Spectre open_visual     search word     [C] I",
  --     "  :Spectre open_file       search in file  [C] I",
  --     "  <CR>           go to match (in Spectre)  [S] B",
  --     "  dd             toggle match (in Spectre) [S] I",
  --     "  <leader>R      replace all (in Spectre)  [S] I",
  --     "",
  --     "  Trouble (diagnostics list)",
  --     "  :Trouble diagnostics toggle    all diag  [C] B",
  --     "  :Trouble diagnostics toggle filter.buf=0 [C] I",
  --     "  :Trouble symbols toggle        symbols   [C] I",
  --     "  :Trouble lsp toggle            LSP defs  [C] I",
  --   },
  -- },
  -- {
  --   title = "Editing & UI Plugins [24/25]",
  --   lines = {
  --     "  Conform (auto-format on save)",
  --     "  :ConformInfo           show formatters   [C] I",
  --     "",
  --     "  Commentary (vim-commentary)",
  --     "  gcc             toggle comment line      [N] B",
  --     "  gc{motion}      toggle comment motion    [N] B",
  --     "  gc              toggle comment           [V] B",
  --     "",
  --     "  Autopairs (auto-close brackets/quotes)",
  --     "",
  --     "  Bufferline (buffer tabs)",
  --     "  :BufferLineCycleNext    next buffer tab  [C] B",
  --     "  :BufferLineCyclePrev    prev buffer tab  [C] B",
  --     "  :BufferLineCloseOthers  close others     [C] I",
  --     "  :BufferLinePick         pick buffer      [C] I",
  --     "  :BufferLinePickClose    pick to close    [C] I",
  --     "",
  --     "  Markdown Preview",
  --     "  :MarkdownPreviewToggle  open in browser  [C] B",
  --     "",
  --     "  Rest.nvim (HTTP client)",
  --     "  :Rest run       run request under cursor [C] B",
  --     "  :Rest last      re-run last request      [C] I",
  --   },
  -- },
  -- {
  --   title = "Misc Plugins [25/25]",
  --   lines = {
  --     "  Rustaceanvim",
  --     "  :RustAnalyzer start     start analyzer   [C] B",
  --     "  :RustAnalyzer stop      stop analyzer    [C] I",
  --     "  :RustAnalyzer restart   restart analyzer [C] B",
  --     "  :RustLsp expandMacro    expand macro     [C] I",
  --     "  :RustLsp moveItem up    move item up     [C] I",
  --     "  :RustLsp moveItem down  move item down   [C] I",
  --     "  :RustLsp joinLines      join lines       [C] I",
  --     "  :RustLsp openCargo      open Cargo.toml  [C] I",
  --     "  :RustLsp parentModule   go to parent mod [C] I",
  --     "  :RustLsp explainError   explain error    [C] I",
  --     "  :RustLsp runnables      run targets      [C] I",
  --     "  :RustLsp debuggables    debug targets    [C] I",
  --     "",
  --     "  jj.nvim (Jujutsu VCS)",
  --     "  :JJ diff        show jj diff             [C] I",
  --     "",
  --     "  Mermaid.nvim",
  --     "  :Mermaid        render diagram           [C] I",
  --     "",
  --     "  Colorizer (nvim-colorizer)",
  --     "  :ColorizerToggle  toggle color preview   [C] I",
  --     "",
  --     "  Indent Blankline",
  --     "  :IBLToggle        toggle indent guides   [C] I",
  --   },
  -- },
}

function open_cheatsheet(start_page)
  local current = start_page or 1
  local buf = vim.api.nvim_create_buf(false, true)

  local width = math.min(50, vim.o.columns - 4)
  local height = math.min(22, vim.o.lines - 4)
  local row = math.floor((vim.o.lines - height) / 2)
  local col = math.floor((vim.o.columns - width) / 2)

  local win = vim.api.nvim_open_win(buf, true, {
    relative = "editor",
    width = width, height = height,
    row = row, col = col,
    style = "minimal", border = "rounded",
    title = " Cheatsheet ", title_pos = "center",
    footer = " Tab/S-Tab · q to close ", footer_pos = "center",
  })

  local function render()
    local page = pages[current]
    local content = { "", "  " .. page.title, "  " .. string.rep("─", width - 4), "" }
    for _, line in ipairs(page.lines) do
      table.insert(content, line)
    end
    vim.bo[buf].modifiable = true
    vim.api.nvim_buf_set_lines(buf, 0, -1, false, content)
    vim.bo[buf].modifiable = false
  end

  render()

  local opts = { buffer = buf, silent = true, nowait = true }
  vim.keymap.set("n", "q", function() vim.api.nvim_win_close(win, true) end, opts)
  vim.keymap.set("n", "<Esc>", function() vim.api.nvim_win_close(win, true) end, opts)
  vim.keymap.set("n", "<Tab>", function()
    current = current % #pages + 1
    render()
  end, opts)
  vim.keymap.set("n", "<S-Tab>", function()
    current = (current - 2) % #pages + 1
    render()
  end, opts)
end
