keys:
  users: &age_keys
    - &sponge age1dzwegqyge33deld53k5cvc0gnwulp9xl3nhqdd7a9y8zcjaq7aqqrr67mn
    - &squid age1vxct33xvtg6djlc3gqey6zs5x739hw02h0yr592yxgpfq8mxl9kszaz50y
  yubikey: &pgp_keys
    - &yubikey_01 0DB7ED7215C5C360
    - &yubikey_02 7E6CCC0E857180EF
creation_rules:
  - path_regex: nixos/common/secrets.ya?ml$
    key_groups:
      - age:
          - *sponge
          - *squid
        pgp:
          - *yubikey_01
          - *yubikey_02
  - path_regex: hosts/octopus/secrets.ya?ml$
    key_groups:
      - pgp:
          - *yubikey_01
          - *yubikey_02
  - path_regex: hosts/coral/secrets.ya?ml$
    key_groups:
      - pgp:
          - *yubikey_01
          - *yubikey_02
