keys:
  age_access: &age_keys
    - &sponge age1dzwegqyge33deld53k5cvc0gnwulp9xl3nhqdd7a9y8zcjaq7aqqrr67mn
    - &squid age1fls2addadr7m0mecsqguwfzvqskt93575wn5atu83zvtgtgv0cqqd5kumv
    - &coral age1t3t4llqc4fmrsr3x4apuz5utctjm82vdez7pztrfcytjyghr3quqsgs776
    - &krill age1vvfmted43wwp548z7sld9gcdcn6wy3dmv6r7m7yzyqwdq5rwnd4swe53uf
  gpg_access: &pgp_keys
    - &yubikey 704592C4592CD51F
creation_rules:
  - path_regex: modules/secrets/sponge.ya?ml$
    key_groups:
      - age: [*sponge, *squid]
        pgp: [*yubikey]
  - path_regex: modules/secrets/squid.ya?ml$
    key_groups:
      - age: [*squid, *sponge]
        pgp: [*yubikey]
  - path_regex: modules/secrets/coral.ya?ml$
    key_groups:
      - age: [*coral, *squid, *sponge]
        pgp: [*yubikey]
  - path_regex: modules/secrets/krill.ya?ml$
    key_groups:
      - age: [*krill, *squid, *sponge]
        pgp: [*yubikey]
  - path_regex: modules/secrets/netrc.ya?ml$
    key_groups:
      - age: [*sponge, *squid, *coral, *krill]
        pgp: [*yubikey]
