keys:
  users: &age_keys
    - &sponge age1dzwegqyge33deld53k5cvc0gnwulp9xl3nhqdd7a9y8zcjaq7aqqrr67mn
    - &squid age1vxct33xvtg6djlc3gqey6zs5x739hw02h0yr592yxgpfq8mxl9kszaz50y
    - &octopus age1gxeewr0vqtxdkjgqvkzhc7kem9fatxyqvk52xpg7cp2rrc4u84hsanmtgs
    - &wip age17xh73q74tej3h942cc6saqd4fejpuxn37w8493f37tass92h4gms6p86t3
  yubikey: &pgp_keys
    - &yubikey 0DB7ED7215C5C360
creation_rules:
  - path_regex: nixos/common/secrets.ya?ml$
    key_groups:
      - age:
          - *sponge
          - *squid
          - *octopus
          - *wip
        pgp:
          - *yubikey
  - path_regex: hosts/octopus/secrets.ya?ml$
    key_groups:
      - age:
          - *octopus
        pgp:
          - *yubikey
