gmail-oauth2-client-secret: ENC[AES256_GCM,data:4kUq6JhOFwVlgttu4UtpKTFDJ8unttZyG5Nqp/7svXHgWFs=,iv:NtzCxK58Fo000FqSwMgfO9S0kysHrA55tKPN2dOE1oE=,tag:WwSI9vJv/F2RxEeC3Qn2QA==,type:str]
gmail-oauth2-client-id: ENC[AES256_GCM,data:fv7611oJ2oQIYqdOyLDXyOOtESPyBNScLXpccI9lTqMzA28sMgboCQskFZ1Uc5TUkYlXaWKU4Kr8JeY3T8iHE5NQjE5afHRP,iv:y3owOQzu4aHa8q/EwZruCnYkNA6+7aYAc8pyq6Gw1Mw=,tag:OdOX9YYPUnQ+DJ2JJzSinw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArL0FKdkhtZ1NNd2YxWCtW
            KzkwT0t6eUIzaEZZckhtVGs0ZFM4WWdxeTFZCkpkLzdsUU81MEZ4UStOb3g4U3p4
            aG15MTVrL2MzUkVXUkxycXRwdEtoYkkKLS0tIFpqcGZ1L3RFR2ZMcDZlR0RscHYw
            dmQwNG13bjArUkxQZEIxY0ZjTlZPRTQK/huILQMgXTmWtbWsPg8/x0FORz+hI6r6
            6wyMBqX7uWLaXZAbgJ1Kf+DRVRmo0AKWpLJH3D27WrLzphexRrEejg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1dzwegqyge33deld53k5cvc0gnwulp9xl3nhqdd7a9y8zcjaq7aqqrr67mn
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5dzhxSVVvVCtZMXVpaUVQ
            Z2JoclNtc2tlUGJMS2dnajI2MXRtRjJnYTM4CmJQOUFiYlFNVVFCcFJkcGpuNmNS
            WFR3NmNNeHRjQ1RUVDhEbCsyYVNVMzgKLS0tIHlxNDdnelhEckF6bktHL3FCaFpm
            RVR3TExLSWQ3dmF6R1E0ZXE2UXhVencKjUEvD+Ir6FPPaU2fGxqhr4DFbMeXiibY
            EBjyiCNT8dVgdFub2zlgoWG0EBLImoGsqFifCPhmbSShJGK5Hbw3Vw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fls2addadr7m0mecsqguwfzvqskt93575wn5atu83zvtgtgv0cqqd5kumv
    lastmodified: "2026-06-25T09:32:02Z"
    mac: ENC[AES256_GCM,data:R5sWcHRFq14re1HMhKAsb77w/zK97cA85O2RUciikLI/+JoNfTm1KyQ4ERqihWB8iB7+gtqUdOfQ5MbUDJwQgo98/4yCRaHhkxSZqPUaQ6ZPPvLx3b6ogf/SEmD6+lD06s4BLu9cgM6GZ78xg/SMNrCw9JTQ6KbqmDkVQqd13bM=,iv:62n1m620FbSk6ysdSSmEo5VLVB5TWOIH4Kx+VbiuvaY=,tag:GVadfFybKX/tUT1Iwz3ang==,type:str]
    pgp:
        - created_at: "2026-06-18T14:11:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hF4DcEWSxFks1R8SAQdA3fBhy8sfdCdzYy2np6eo2THMjqMlZzTNWENfYZtZInUw
            LzHVqLE7YZrzlXzdB0yHiW+IJnne9TYfpPIR1QKQETc5AI5C25wXYeyN8C2Ugbs9
            0lwB7rArolVHfFFLLiDeuq+rYONvrqyHsC9R3dqOVdWnXmvdUK926GjsUORJPzDZ
            7wKKF75k2iMFSHsuVg6gO1DuwVrcS0occKR+lzja5dOi2XQZS4hmoso9tPhN6w==
            =qBJV
            -----END PGP MESSAGE-----
          fp: 704592C4592CD51F
    unencrypted_suffix: _unencrypted
    version: 3.13.1
