{ lib, ... }:
let inherit (lib) mkOption types;
in {
  options.u2f.mappings = mkOption {
    type = types.attrsOf types.str;
    default = { };
    example = {
      wallago = "wallago:Ge4frHn...==";
      alice = "alice:J123abc...==";
    };
    description = ''
      Defines the PAM U2F mapping line for a user. 
      An attribute set mapping each user to their U2F registration string,
      as generated by `pamu2fcfg` tool after setting up a U2F or FIDO2 key.

      Format: `username:keyHandle,publicKey,[options]`

      Example command to generate: `pamu2fcfg -u wallago`
    '';
  };
}
