{ lib, ... }:
let
  inherit (lib) mkOption types;
in
{
  options.wg-client = {
    privateKeyFile = mkOption {
      type = types.path;
      example = "./wg/pk.key";
      description = ''
        Set private key path (generated by: wg genkey).
      '';
    };
    ip = mkOption {
      type = types.str;
      default = "10.100.0.2/24";
      description = ''
        Set IP.
      '';
    };
  };
}
